name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/keymap_draser.yml"
      - "keymap_drawer.config.yaml"
      - "config/**"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      amend_commit: false
      install_branch: "main"
      keymap_patterns: "config/*.keymap"
      json_path: ""
      config_path: "keymap_drawer.config.yaml" # config file, ignored if not exists
      output_folder: "keymap-drawer"
      destination: "both"
      parse_args: "" # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
      draw_args: "cygnus:'--dts-layout config/boards/shields/cygnus/cygnus-layouts.dtsi'"
      debug_mode: true
  create_png:
    runs-on: ubuntu-latest
    needs:
      - draw
    steps:
      - name: Install PNG Image Tools
        run: |
          mkdir -p "$HOME/.local/bin"
          curl -O 'https://download.imagemagick.org/ImageMagick/download/binaries/magick'
          chmod u+x magick
          mv magick "$HOME/.local/bin"
          echo "magick --version"
          $HOME/.local/bin/magick --version
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          sudo apt-get install -qq -y inkscape
      - uses: actions/checkout@v4
      - run: |
          git config --global user.email "linrongbin16@outlook.com"
          git config --global user.name "linrongbin16"
          git pull
      - name: Generate PNG
        run: |
          # Use 5x times density for bigger PNG, by default is 96
          magick -density 480 ./keymap-drawer/cygnus.svg ./keymap-drawer/cygnus.png
          echo "git status"
          git status
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(png): auto-create png image"
          file_pattern: "keymap-drawer/cygnus.png"
